### ISSUE TITLE
리액트 예제 실행이 안되고 있습니다.

### ISSUE THREAD

**Issue by kyunggyuyeol** [bjpublic/Reactnative#1]
D:\SampleApp>react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 864 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
info Launching emulator...
error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...
> Task :app:installDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
27 actionable tasks: 27 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No connected devices!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s

error Failed to install the app. Make sure you have an Android emulator running or a device connected. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No connected devices!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s

    at checkExecSyncError (child_process.js:609:11)
    at execFileSync (child_process.js:627:15)
    at runOnAllDevices (D:\SampleApp\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by dev-yakuza** [comment]
안녕하세요

Android X 대응을 위해 Jetitier를 설치하여 실행할 필요가 있어 보입니다.

- [Jetifier](https://www.npmjs.com/package/jetifier)

## Jetifier 설치

아래에 명령어로 Jetifier를 설치합니다.

```bash
npm install --save-dev jetifier
```

## 프로젝트 실행

아래에 명령어를 사용하여 프로젝트를 실행합니다.

- Jetifier 실행

```bash
npx jetify
```

- 프로젝트 실행

```bash
npm run android
```

## package.json 설정

프로젝트 실행시 매번 Jetifier를 실행해야 하므로 `package.json`을 아래와 같이 수정합니다.

```json
...
"scripts": {
    ...
    "preandroid": "npx jetify",
    "android": "react-native run-android",
    ...
},
...
```

그리고 프로젝트를 실행할 시 아래에 명령어를 사용합니다.

```bash
npm run android
```

여기서 `preandroid`는 android 스크립트를 실행하기 전에 실행하는 스크립트입니다.

이걸로 문제가 해결되셨으면 좋겠네요

감사합니다.

**Comment by kyunggyuyeol** [comment]
실행하는 데는 성공했으나 리액트 기본 앱이 실행이 안됩니다 ....
![제목 없음](https://user-images.githubusercontent.com/19888702/70718113-f7221e00-1d32-11ea-9849-83ac9deaaf5d.png)

**Comment by dev-yakuza** [comment]
안녕하세요 

불편을 드려 죄송합니다. 환경설정이 가장 어렵습니다.ㅠㅠ

아마 아래에 링크의 이슈랑 관련이 있는거 같습니다.

[https://github.com/bjpublic/Reactnative/issues/2](https://github.com/bjpublic/Reactnative/issues/2)

아마 노드 버전 문제일 확률이 높습니다. 위의 링크에 해결 방법이 있으므로 참고하시기 바랍니다.

감사합니다.

**Comment by dev-yakuza** [comment]
해결하셔서 다행이네요...책을 쓸때 노드 버전도 명기를 해야할 거 같네요.ㅠㅠ

감사합니다!
