### ISSUE TITLE
안드로이드 에뮬레이터로 안되네요

### ISSUE THREAD

**Issue by starguys** [bjpublic/Reactnative#14]
warn No apps connected. Sending "reload" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB.

node.npm.choco 다 최신버전으로 깔았고

expo로는 잘 사용되는대 npm run android로는 사용이 안됩니다.

안드로이드 스튜디오로 에뮬레이터 열고 npm run android를 해보니까 흰화면만 나옵니다.

**Comment by starguys** [comment]
그냥 expo로 할려고 하는게 큰문제가 있을까요?

**Comment by dev-yakuza** [comment]
안녕하세요 @starguys 

우선 책 구매 너무너무 감사합니다.

> 그냥 expo로 할려고 하는게 큰문제가 있을까요?

이번 책은 react-native-cli 기준으로 작성되었기 때문에, Expo로 진행이 어려우실거 같습니다. 소스코드는 그대로 활용이 가능하실 수 있으나, 외부 라이브러리를 설치하여 사용하는 부분에서 많은 문제를 겪으실 거 같습니다.

- 혹시 node lts버전으로 설치하셨나요?

https://chocolatey.org/packages/nodejs-lts

- 아래에 명령어를 시도해 보시겠어요?

```bash
npm run android
adb reverse tcp:8081 tcp:8081
```

- 아래에 명령어로 새로운 프로젝트를 생성하시고 시도해 보시겠어요?

```bash
react-native init NewProject
cd NewProject
npm run android
```

**Comment by starguys** [comment]
다행히 출근전에 화면 이유는 못찾았지만 띄우는거 까지는 성공을 해서 퇴근후 다시 봐봐야 할것 같아요

**Comment by dev-yakuza** [comment]
@starguys
다행이십니다. 😭

혹시 해결 방법이 기억나시면, 다른 분들을 위해 공유 부탁드립니다!
(이슈도 Close도 부탁드립니다.) 🙇‍♂️ 

또 문제가 있으시면, 이슈나 dev.yakuza@gmail.com으로 연락주시기 바랍니다.
감사합니다
