### ISSUE TITLE
7장 날씨앱을 제작하는 중 에러가 발생하여 문의드립니다..!

### ISSUE THREAD

**Issue by imseongtae** [bjpublic/Reactnative#15]
![image](https://user-images.githubusercontent.com/60806840/87393546-4db54a80-c5e9-11ea-969f-f4cbc8544cf6.png)

7장 날씨앱을 제작하는 중 아래와 같은 에러가 발생하여 문의드립니다. ㅠ..  
```bash
[!] No podspec found for `react-native-geolocation` in `../node_modules/@react-native-community/geolocation
```

iOS 에서 react-native-geolocation 을 사용하여 위치 정보를 습득하기 위해서는 코코아 포드를 통해 필요한 라이브러리를 링크해야 한다고 하는데..! 링크가 되지 않습니다. react-native 시작한지 얼마되지 않아서 어떠한 키워드로 에러를 검색해야 하는지 몰라서 저자님께 여쭙니다..ㅠ  
교재와 마찬가지로 `ios/` 폴더로 경로를 변경한 후 아래 명령어를 실행했습니다. ㅠ 
이 명령어 이후에 `ios/` 폴더 하위에 `Weather` 라는 폴더가 생겨야 다음 과정을 진행할 수 있을 것 같은데..   
다음 과정으로 진행할 수 있는 방법이 있을까요?

```bash
# cd ios
pod install
```

**Comment by dev-yakuza** [comment]
안녕하세요 @imseongtae 님

우선 책 구매해주셔서 너무너무 감사합니다. 🙇‍♂️ 

그리고 불편을 드려서 죄송합니다. 최근 React Native와 iOS의 업데이트로 변경사항이 발생하였습니다. 😭 

react-native-geolocation 설치를 아래에 블로그를 참고하셔서 진행해 주시기 바랍니다.

- [React Native에서 현재 위치 정보 가져오기](https://dev-yakuza.github.io/ko/react-native/react-native-geolocation-service/)

여러가지 충돌의 문제가 발생할 수 있어서 현재까지 진행하신 프로젝트는 지우시고 새롭게 진행하시는 걸 권장합니다. 🙏 

다시 한번 불편을 드려서 죄송합니다. 🙇‍♂️ 

감사합니다.

**Comment by imseongtae** [comment]
네 안녕하세요~!🙇‍♂️  @dev-yakuza 님 

친절하게 답변해주셔서 감사합니다. 😁
말씀해주신대로 프로젝트는 지우고 새롭게 진행하겠습니다🏃

고맙습니다. 항상 건강하세요~!🙏
