### ISSUE TITLE
[Page 62 - 안드로이드, 윈도우] Unable to load script. Make sure you're either running a Metro server

### ISSUE THREAD

**Issue by dev-yakuza** [bjpublic/Reactnative#2]
안녕하세요.
스무디 한잔 리액트 네이티브 구매자입니다.
62페이지 쯤에서 자꾸 오류가 나서 진행이 안됩니다. ㅠ_ㅠ..

윈도우환경의 안드로이드 에뮬레이터로 진행중이며,

npm run android 명령어를 치면,
Unable to load script. Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.

라고 빨간 배경에 흰색 텍스트로 에러메시지가 뜹니다.

메트로 서버가 움직이고 있다던지 패키지가 정확하게 있는지 확인하라는데, 뭘 어찌해야할지 모르겠습니다.

이상입니다. 감사합니다.

**Comment by dev-yakuza** [comment]
해결 방법

1. 프로젝트를 초기화한 후 시도해 보시기 바랍니다.
[https://github.com/facebook/react-native/issues/25348](https://github.com/facebook/react-native/issues/25348)

- Clear watchman watches: ```watchman watch-del-all```
- Delete the node_modules folder: ```rm -rf node_modules && npm install```
- Reset Metro Bundler cache: ```rm -rf /tmp/metro-bundler-cache-* or npm start -- --reset-cache```
- Remove haste cache: ```rm -rf /tmp/haste-map-react-native-packager-*```

2. 안드로이드 에뮬레이터 또는 디바이스와 서버를 연결하는 명령어 입니다. 이 명령어를 사용하여 서버와 에뮬레이터 연결을 시도해 보시기 바랍니다.
[https://stackoverflow.com/questions/32572399/android-failed-to-load-js-bundle](https://stackoverflow.com/questions/32572399/android-failed-to-load-js-bundle)

```
adb reverse tcp:8081 tcp:8081 
```

3. nodejs의 버전 문제일 가능성이 있습니다. 아래에 노드 버전을 설치해 보시기 바랍니다.

[https://stackoverflow.com/questions/55441230/unable-to-load-script-make-sure-you-are-either-running-a-metro-server-or-that-yo](https://stackoverflow.com/questions/55441230/unable-to-load-script-make-sure-you-are-either-running-a-metro-server-or-that-yo)

1- Try to downgrade your Node version (current version is 12.13.1)

```
choco uninstall nodejs
choco install nodejs --version 12.8
```

**Comment by dev-yakuza** [comment]
검색해주신 3개의 해결안 중에서 테스트 후 결과입니다.

1번 해결안은 제가 윈도우 운영체제라 테스트는 못해봤습니다.
2번 해결안은 테스트해봤지만, 달라지지 않았습니다.
3번 해결안 테스트해봤는데, 다행히도 리액트 기본 창이 떴습니다.

아참.. 한개 정보를 누락시켰었네요.

```
  Run instructions for iOS:

    • cd C:\dev\FirstApp2 && npx react-native run-ios

    - or -

    • Open FirstApp2\ios\FirstApp2.xcodeproj in Xcode or run "xed -b ios"

    • Hit the Run button

 

  Run instructions for Android:

    • Have an Android emulator running (quickest way to get started), or a device connected.

    • cd C:\dev\FirstApp2 && npx react-native run-android
```

npm run android 명령어로는 오류메세지가 뜨니, 위와 같이 npx react-native run-android 로 해야 합니다. 

정리하자면

1. 기존의 앱 (폴더) 삭제
2. NodeJS 12.8버젼으로 재설치 
```
choco uninstall nodejs
choco install nodejs --version 12.8
```
3. react-native init FirstApp
4. cd C:\dev\FirstApp
5. npx react-native run-android

이 절차입니다.

**Comment by dev-yakuza** [comment]
윈도우 환경에서 안드로이드 에뮬레이터로 실행할 시 문제가 있던 분고의 메일 내용을 공유합니다.

혹시 동일한 문제가 있으신 분들은 참고하셨으면 좋겠습니다.

**Comment by kyunggyuyeol** [comment]
node.js 가 문제 였군요 ....

![제목 없음](https://user-images.githubusercontent.com/19888702/70770343-5d00bb00-1db0-11ea-9a1a-8c686b7ff272.png)


해결되었습니다.

**Comment by dev-yakuza** [comment]
> node.js 가 문제 였군요 ....
> 
> ![제목 없음](https://user-images.githubusercontent.com/19888702/70770343-5d00bb00-1db0-11ea-9a1a-8c686b7ff272.png)
> 
> 해결되었습니다.

해결하셨다니 다행이네요.ㅠㅠ

이제 어려운 부분 넘으셨으니 책과 함께 앱 개발 세계에 빠져보시기 바랍니다~!

감사합니다.
