### ISSUE TITLE
[질문] component 생성 시에 디렉토리/index.tsx 구조를 사용하는 이유가 궁금합니다.

### ISSUE THREAD

**Issue by sh0seo** [bjpublic/Reactnative#29]
리디북스에서 책을 구매하여 공부하고 있는 개발자입니다.

책의 예제들을 보면 **디렉토리/index.tsx** 형태로 사용하시는데요. 이렇게 사용하는 이유가 궁금합니다.

**Comment by dev-yakuza** [comment]
@sh0seo

안녕하세요.
질문주신 부분은 개인적인 취향 부분이 있습니다.
저는 **디렉토리/index.tsx**뿐만 아니라 storybook 파일, test 파일 등을 함께 보관하기 때문에 이와 같은 형식을 사용하고 있습니다.

```bash
Button/index.tsx
Button/index.test.tsx
Button/index.stories.tsx
```

그리고 만약 Button 컴포넌트에 종속되는 컴포넌트를 만들때에도 해당 구조를 가지고 있으면 관리가 쉽다고 생각했습니다.

```bash
Button/index.tsx
Button/index.test.tsx
Button/index.stories.tsx
Button/Icon/index.tsx
Button/Icon/index.test.tsx
Button/Icon/index.stories.tsx
```

강제적인 규칙이 아니므로, 편하신 방식으로 사용하시면 좋을거 같습니다.

감사합니다.

**Comment by sh0seo** [comment]
@dev-yakuza 

답변 감사합니다. 
말씀하신데로 함께 관리할 수 있는 장점이 있군요. 

좋은 개발팁 감사합니다.
